//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cornball.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cornball.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal of The Cornball is to put all the cards in order from 2 to king with one color on each line. What color is put on each line does not matter.Twos can only be put in a gap on the far left on the board. Other cards can only be put in a gap to the right of the card in the same color that is right before in order. No card can be put in a gap after the king.
        ///
        ///Drag a card to the right gap or double-click the card to automatically find the right place. Click on a gap and the right card for that gap will  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cornball.
        /// </summary>
        public static string Cornball {
            get {
                return ResourceManager.GetString("Cornball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You failed to complete The Cornball!
        ///
        ///Score: {0}
        ///Moves: {1}.
        /// </summary>
        public static string GameLoseText {
            get {
                return ResourceManager.GetString("GameLoseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!.
        /// </summary>
        public static string GameLoseTitle {
            get {
                return ResourceManager.GetString("GameLoseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking high score....
        /// </summary>
        public static string GameWinChecking {
            get {
                return ResourceManager.GetString("GameWinChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You made it to the high score list! Enter your name to send your score..
        /// </summary>
        public static string GameWinHigh {
            get {
                return ResourceManager.GetString("GameWinHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately you did not set a high score this time..
        /// </summary>
        public static string GameWinNoHigh {
            get {
                return ResourceManager.GetString("GameWinNoHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You put all cards on the right place and finished The Cornball!
        ///
        ///Round: {0}
        ///Score: {1}
        ///Moves: {2}.
        /// </summary>
        public static string GameWinText {
            get {
                return ResourceManager.GetString("GameWinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string GameWinTitle {
            get {
                return ResourceManager.GetString("GameWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High score in {0}: {1} ({2}).
        /// </summary>
        public static string HighestScore {
            get {
                return ResourceManager.GetString("HighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High score in {0}: loading....
        /// </summary>
        public static string HighestScoreLoading {
            get {
                return ResourceManager.GetString("HighestScoreLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High score.
        /// </summary>
        public static string HighScore {
            get {
                return ResourceManager.GetString("HighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time high.
        /// </summary>
        public static string HighScoreAllTime {
            get {
                return ResourceManager.GetString("HighScoreAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best in {0}.
        /// </summary>
        public static string HighScoreMonth {
            get {
                return ResourceManager.GetString("HighScoreMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more moves can be done, the cards are being reshuffled. 1 round to go.
        ///
        ///Score: {0}
        ///Moves: {1}.
        /// </summary>
        public static string LastRoundEndText {
            get {
                return ResourceManager.GetString("LastRoundEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules and information.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show high score.
        /// </summary>
        public static string MenuHighScore {
            get {
                return ResourceManager.GetString("MenuHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new game.
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound on/off.
        /// </summary>
        public static string MenuSound {
            get {
                return ResourceManager.GetString("MenuSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statistics.
        /// </summary>
        public static string MenuStatistics {
            get {
                return ResourceManager.GetString("MenuStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last move.
        /// </summary>
        public static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves.
        /// </summary>
        public static string Moves {
            get {
                return ResourceManager.GetString("Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more moves can be done, the cards are being reshuffled. {2} rounds to go.
        ///
        ///Score: {0}
        ///Moves: {1}.
        /// </summary>
        public static string RoundEndText {
            get {
                return ResourceManager.GetString("RoundEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of round {0}.
        /// </summary>
        public static string RoundEndTitle {
            get {
                return ResourceManager.GetString("RoundEndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost games.
        /// </summary>
        public static string StatisticsLost {
            get {
                return ResourceManager.GetString("StatisticsLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played games.
        /// </summary>
        public static string StatisticsPlayed {
            get {
                return ResourceManager.GetString("StatisticsPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed in round {0}.
        /// </summary>
        public static string StatisticsWonRound {
            get {
                return ResourceManager.GetString("StatisticsWonRound", resourceCulture);
            }
        }
    }
}
